### ISSUE TITLE
Howto make the instance a little bit more persistant.

### ISSUE THREAD

**Issue by damarges** [OliverKohlDSc/dockerhub_ubuntu-headless-desktop-vnc#1]
Got the docker run line converted to a nice docker-compose.yml and bound some volumes to it. Is there a chance to make this instance a little more persistant, meaning that after I started the container, did a apt update and apt upgrade then shutdown the container and get it back up running in exactly that state without the need to to the whole update action again?

**Comment by OliverKohlDSc** [comment]
Yes, that's possible. Docker supports both a RUN and a CMD command. Moreover, I'd recommend to having a look at the lifecycle events of a container.
